/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#f59e0b",
        "secondary-fixed": "#d9e3f7",
        "on-error": "#ffffff",
        "on-primary-container": "#613b00",
        "inverse-on-surface": "#edf0ff",
        "tertiary-container": "#1abdff",
        "primary-fixed-dim": "#ffb95f",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001e2d",
        "secondary-container": "#d6e0f4",
        "outline-variant": "#d8c3ad",
        "on-secondary-fixed-variant": "#3d4757",
        "surface-variant": "#dce2f7",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-dim": "#d3daef",
        "on-surface": "#141b2b",
        "on-background": "#141b2b",
        "surface-container-low": "#f1f3ff",
        "on-secondary-fixed": "#121c2a",
        "inverse-primary": "#ffb95f",
        "surface": "#f9f9ff",
        "outline": "#867461",
        "on-primary-fixed": "#2a1700",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#7fd0ff",
        "primary-fixed": "#ffddb8",
        "primary": "#855300",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bdc7db",
        "surface-tint": "#855300",
        "tertiary-fixed": "#c5e7ff",
        "on-primary-fixed-variant": "#653e00",
        "on-primary": "#ffffff",
        "surface-container-high": "#e1e8fd",
        "on-secondary-container": "#596374",
        "surface-container-highest": "#dce2f7",
        "tertiary": "#00658b",
        "on-tertiary-fixed-variant": "#004c6a",
        "background": "#f9f9ff",
        "surface-container": "#e9edff",
        "secondary": "#555f70",
        "on-surface-variant": "#534434",
        "surface-bright": "#f9f9ff",
        "on-tertiary-container": "#004966",
        "inverse-surface": "#293040"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
